# Generated by Django 4.2.6 on 2024-03-02 01:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="articel_type",
        ),
        migrations.RemoveField(
            model_name="product",
            name="gender_cat",
        ),
        migrations.RemoveField(
            model_name="product",
            name="sub_cat",
        ),
    ]
