# Generated by Django 3.2 on 2024-04-08 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_product_completelook'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_forecast',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
