# Generated by Django 4.2.6 on 2024-03-02 01:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0002_remove_product_articel_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="articel_type",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="gender_cat",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="sub_cat",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
