# Generated by Django 3.2 on 2024-03-31 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20240330_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation', to='cart.product')),
                ('recommended_products', models.ManyToManyField(blank=True, related_name='recommended_by', to='cart.Product')),
            ],
        ),
    ]
