# Generated by Django 3.2 on 2024-03-31 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_productrecommendation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='articel_type',
            new_name='article_type',
        ),
    ]
